# Generated by Django 4.2.9 on 2024-03-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20)),
                ('perference', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Afternoon_Activity',
            fields=[
                ('date', models.DateField(editable=False, primary_key=True, serialize=False)),
                ('second_activity', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_with_perference', to='afternoon_activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_number', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cabin_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselors_cabin', to='afternoon_activity.cabin')),
                ('possition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possition_afternoon_activity', to='afternoon_activity.afternoon_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('afternoon_activity', models.ManyToManyField(related_name='afternoon_activity_selected', to='afternoon_activity.afternoon_activity')),
                ('cabin_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_for_camper', to='afternoon_activity.cabin')),
                ('counselor', models.ManyToManyField(related_name='campers_counselor', to='afternoon_activity.counselor')),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='camper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camper_in_cabin', to='afternoon_activity.camper'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_in_cabin', to='afternoon_activity.counselor'),
        ),
        migrations.AddField(
            model_name='afternoon_activity',
            name='activity_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_in_afternoon_activity', to='afternoon_activity.counselor'),
        ),
        migrations.AddField(
            model_name='afternoon_activity',
            name='camper',
            field=models.ManyToManyField(related_name='camper_in_activity', to='afternoon_activity.camper'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('perference__gte', 0), ('perference__lte', 3)), name='perference_in_range'),
        ),
    ]
