# Generated by Django 4.2.9 on 2024-03-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Afternoon_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('second_activity', models.BooleanField(default=False)),
                ('perference', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_with_perference', to='afternoon_activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_for_camper', to='afternoon_activity.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselors_cabin', to='afternoon_activity.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Campers_Afternoon_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afternoon_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_for_camper', to='afternoon_activity.afternoon_activity')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camper_in_activity', to='afternoon_activity.camper')),
            ],
        ),
        migrations.AddConstraint(
            model_name='afternoon_activity',
            constraint=models.CheckConstraint(check=models.Q(('perference__gte', 0), ('perference__lte', 3)), name='perference_in_range'),
        ),
    ]
