# Generated by Django 4.2.9 on 2024-07-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=30)),
                ('rainy_day', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('cabin_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.ManyToManyField(blank=True, related_name='cabins_in_group', to='afternoon_activity.cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afternoon_activity.cabin')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afternoon_activity.session')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainy_day', models.BooleanField(default=False)),
                ('spots_left', models.IntegerField(blank=True, default=None, help_text="Will be automatically overwritten upon creation with 'max_participants' for the activity in question.", null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity', to='afternoon_activity.activity')),
                ('allowed_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group')),
                ('campers', models.ManyToManyField(blank=True, related_name='camper_in_activity', to='afternoon_activity.camper')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity_period', to='afternoon_activity.period')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('afternoon_role', models.ManyToManyField(blank=True, related_name='counselor_for_activity', to='afternoon_activity.programactivity')),
                ('sessionCabin', models.ManyToManyField(blank=True, related_name='counselors_for_session_cabin', to='afternoon_activity.sessioncabin')),
            ],
        ),
        migrations.AddField(
            model_name='camper',
            name='session_cabin',
            field=models.ManyToManyField(blank=True, related_name='sessioncabin_for_camper', to='afternoon_activity.sessioncabin'),
        ),
        migrations.AddConstraint(
            model_name='programactivity',
            constraint=models.CheckConstraint(check=models.Q(('spots_left__gte', 0)), name='spots_left_is_positive'),
        ),
    ]
