# Generated by Django 4.2.9 on 2024-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='week_one',
            field=models.BooleanField(default=True),
        ),
    ]
