# Generated by Django 4.2.9 on 2024-08-06 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='session_cabin',
            field=models.ManyToManyField(related_name='sessioncabin_for_camper', to='afternoon_activity.sessioncabin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ManyToManyField(related_name='cabins_in_group', to='afternoon_activity.cabin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='programactivity',
            name='allowed_groups',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group'),
        ),
        migrations.AlterField(
            model_name='programactivity',
            name='period',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity_period', to='afternoon_activity.period'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(),
        ),
    ]
