# Generated by Django 4.2.14 on 2025-06-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programactivity',
            name='allowed_groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group'),
        ),
        migrations.AddField(
            model_name='programactivity',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity_period', to='afternoon_activity.period'),
        ),
    ]
