# Generated by Django 5.0.3 on 2024-03-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0002_cabin_week_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
                ('group', models.ManyToManyField(related_name='cabins_in_group', to='afternoon_activity.cabin')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='allowed_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group'),
        ),
    ]
