# Generated by Django 4.2.14 on 2025-08-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0002_programactivity_allowed_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camper',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
