# Generated by Django 5.0.3 on 2024-03-26 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0003_activity_max_participants_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='allowed_groups',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group'),
        ),
    ]
