# Generated by Django 4.2.9 on 2024-05-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0006_alter_counselor_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='afternoon_activity',
            name='perference_in_range',
        ),
        migrations.RenameField(
            model_name='afternoon_activity',
            old_name='perference',
            new_name='preference',
        ),
        migrations.AddField(
            model_name='activity',
            name='rainy_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afternoon_activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_with_preference', to='afternoon_activity.activity'),
        ),
        migrations.AddConstraint(
            model_name='afternoon_activity',
            constraint=models.CheckConstraint(check=models.Q(('preference__gte', 0), ('preference__lte', 3)), name='preference_in_range'),
        ),
    ]
