# Generated by Django 4.2.9 on 2024-05-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0007_remove_afternoon_activity_perference_in_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='afternoon_activity',
            name='preference_in_range',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='allowed_groups',
        ),
        migrations.RemoveField(
            model_name='afternoon_activity',
            name='preference',
        ),
        migrations.AddField(
            model_name='afternoon_activity',
            name='allowed_groups',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='group_for_activity', to='afternoon_activity.group'),
        ),
        migrations.AlterField(
            model_name='afternoon_activity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity', to='afternoon_activity.activity'),
        ),
    ]
