# Generated by Django 4.2.9 on 2024-05-10 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0010_alter_afternoon_activity_counselor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afternoon_activity',
            name='counselor',
        ),
        migrations.AddField(
            model_name='counselor',
            name='afternoon_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_for_activity', to='afternoon_activity.afternoon_activity'),
        ),
    ]
