# Generated by Django 4.2.9 on 2024-05-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0012_rename_second_activity_afternoon_activity_second_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoon_activity',
            name='spots_left',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
