# Generated by Django 4.2.9 on 2024-05-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0013_afternoon_activity_spots_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='afternoon_activity',
            old_name='second_period',
            new_name='rainy_day',
        ),
        migrations.AddField(
            model_name='afternoon_activity',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_for_activity', to='afternoon_activity.session'),
        ),
    ]
