# Generated by Django 4.2.9 on 2024-05-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0014_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoon_activity',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_for_activity', to='afternoon_activity.session'),
        ),
    ]
