# Generated by Django 4.2.9 on 2024-05-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0017_period_afternoon_activity_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoon_activity',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_activity_period', to='afternoon_activity.period'),
        ),
    ]
