# Generated by Django 4.2.9 on 2024-05-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0021_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
    ]
