# Generated by Django 4.2.9 on 2024-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0025_remove_counselor_afternoon_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='sessionCabin',
            field=models.ManyToManyField(related_name='counselors_cabin', to='afternoon_activity.sessioncabin'),
        ),
    ]
