# Generated by Django 4.2.9 on 2024-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0026_alter_counselor_sessioncabin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='afternoon_role',
            field=models.ManyToManyField(blank=True, related_name='counselor_for_activity', to='afternoon_activity.afternoon_activity'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='sessionCabin',
            field=models.ManyToManyField(blank=True, related_name='counselors_cabin', to='afternoon_activity.sessioncabin'),
        ),
    ]
