# Generated by Django 4.2.9 on 2024-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0027_alter_counselor_afternoon_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='session_cabin',
        ),
        migrations.AlterField(
            model_name='counselor',
            name='sessionCabin',
            field=models.ManyToManyField(blank=True, related_name='counselors_for_session_cabin', to='afternoon_activity.sessioncabin'),
        ),
        migrations.AddField(
            model_name='camper',
            name='session_cabin',
            field=models.ManyToManyField(related_name='cabin_for_camper', to='afternoon_activity.sessioncabin'),
        ),
    ]
