# Generated by Django 4.2.9 on 2024-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0028_remove_camper_session_cabin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afternoon_activity',
            name='campers',
            field=models.ManyToManyField(blank=True, related_name='camper_associated_with_activity', to='afternoon_activity.camper'),
        ),
        migrations.DeleteModel(
            name='Campers_Afternoon_Relation',
        ),
    ]
