# Generated by Django 4.2.9 on 2024-05-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0029_afternoon_activity_campers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoon_activity',
            name='campers',
            field=models.ManyToManyField(blank=True, related_name='camper_in_activity', to='afternoon_activity.camper'),
        ),
        migrations.AddConstraint(
            model_name='afternoon_activity',
            constraint=models.CheckConstraint(check=models.Q(('spots_left__gte', 0)), name='spots_left_is_positive'),
        ),
    ]
