# Generated by Django 4.2.9 on 2024-05-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0030_alter_afternoon_activity_campers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Afternoon_Activity',
            new_name='ProgramActivity',
        ),
    ]
