# Generated by Django 4.2.9 on 2024-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoon_activity', '0031_rename_afternoon_activity_programactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='session_cabin',
            field=models.ManyToManyField(related_name='sessioncabin_for_camper', to='afternoon_activity.sessioncabin'),
        ),
        migrations.AlterField(
            model_name='programactivity',
            name='spots_left',
            field=models.IntegerField(blank=True, default=None, help_text="Will be automatically overwritten upon creation with 'max_participants' for the activity in question.", null=True),
        ),
    ]
